---
plugin: aws_ec2
aws_profile: default
regions: 
  - us-east-2
keyed_groups:
  - key: tags.Name
ansible_python_interpreter: /usr/bin/python3
filters:
  instance-state-name: running
compose:
  ansible_host: public_ip_address